name: Test Build - Auth Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print to console
        run: echo "Hello Watchdog! ${{secrets.TEST}} ${{github.repository}} ${{env.REGISTRY}}"